const WHITELIST: string[] = [
    // Major Exchanges
    // 'binance.com',
    'coinbase.com',
    'kraken.com',
    'okx.com',
    'huobi.com',
    'kucoin.com',
    'bybit.com',
    'gemini.com',
    'bitfinex.com',
    'bitstamp.net',
    'crypto.com',
    'gate.io',
    'mexc.com',
    'poloniex.com',
    'bittrex.com',
    'bitget.com',
    'deribit.com',
    'ftx.com', // Note: Now bankrupt but included for reference
  
    // Wallets & Security
    'metamask.io',
    'ledger.com',
    'trezor.io',
    'trustwallet.com',
    'argent.xyz',
    'myetherwallet.com',
    'rabby.io',
    'phantom.app',
    'exodus.com',
    'mathwallet.org',
    'tokenpocket.pro',
    'safe.global',
    'walletconnect.com',
    'rainbow.me',
    'zerion.io',
    'imtoken.com',
    'coin98.com',
  
    // DeFi Platforms
    'uniswap.org',
    'aave.com',
    'curve.fi',
    'compound.finance',
    'makerdao.com',
    'yearn.finance',
    'sushi.com',
    'balancer.fi',
    '1inch.io',
    'dydx.exchange',
    'paraswap.io',
    'matcha.xyz',
    'opensea.io',
    'magiceden.io',
    'looksrare.org',
    'blur.io',
    'pancakeswap.finance',
    'traderjoexyz.com',
    'spookyswap.finance',
    'quickswap.exchange',
  
    // Layer 2 & Scaling
    'arbitrum.io',
    'optimism.io',
    'polygon.technology',
    'starknet.io',
    'zksync.io',
    'loopring.org',
  
    // Blockchain Explorers
    'etherscan.io',
    'bscscan.com',
    'arbiscan.io',
    'optimistic.etherscan.io',
    'polygonscan.com',
    'solscan.io',
    'ftmscan.com',
    'snowtrace.io',
    'moonbeam.moonscan.io',
  
    // Infrastructure & Tools
    'infura.io',
    'alchemy.com',
    'thegraph.com',
    'chain.link',
    'moralis.io',
    'quicknode.com',
    'ankr.com',
    'pokt.network',
    'tenderly.co',
    'blocknative.com',
    'blockdaemon.com',
    'nansen.ai',
    'dune.xyz',
    'debank.com',
    'zapper.fi',
    'zerion.io',
  
    // Stablecoins
    'tether.to',
    'circle.com',
    'makerdao.com',
    'paxos.com',
  
    // Security & Audits
    'certik.com',
    'slowmist.com',
    'peckshield.com',
    'quantstamp.com',
    'openzeppelin.com',
    'consensys.net',
    'halborn.com',
  
    // News & Education
    'coingecko.com',
    'coinmarketcap.com',
    'messari.io',
    'theblock.co',
    'decrypt.co',
    'coindesk.com',
    'bankless.com',
    'defipulse.com'
  ];
  
  export default WHITELIST;